clear;
%% Configuration
addpath(genpath(pwd))                           % Set path to all modules
DOF = 16;DOMAIN = 'catmullRom';                 % Degrees of freedom, Catmull-Rom spline domain
d = domain(DOF);                                % Domain configuration
p = defaultParamSet;                            % Base Quality Diversity (QD) configuration (MAP-Elites)
numLatentDims = 2;
m = cfgLatentModel('data/workdir',d.resolution, numLatentDims);% VAE configuration
pm = poemParamSet(p,m);                         % Configure POEM ("Phenotypic niching based Optimization by Evolving a Manifold")
pm.categorize = @(geno,pheno,p,d) predictFeatures(pheno,p.model);  % Anonymous function ptr to phenotypic categorization function (= VAE)

%% Initialize Experiment
% Initialize solution set using space filling Sobol sequence in genetic space
clear matchedParams;
fig = figure(1);ax=gca;
matchedParams(1,:) = [1 1 1 1 1 1 1 1 zeros(1,8)];
matchedParams(2,:) = [1 0.3 1 0.3 1 0.3 1 0.3 zeros(1,8)];

fig(1) = figure(1); hold off; ax = gca;
showPhenotype(matchedParams,d,1.2,ax); axis([-2 2 -2 2]); axis equal;

numShapes = 100;
scaling = [0.1 1.0];

scaleArray = [scaling(1):(scaling(2)-scaling(1))/(numShapes-1):scaling(2)]';

genomes = []; iter = 1;
for i=1:size(matchedParams,1)
    for j=1:length(scaleArray)
        genomes(iter,:) = [scaleArray(j).*matchedParams(i,1:DOF/2) matchedParams(i,DOF/2+1:end)];
        iter = iter + 1;
    end
end

fig(2) = figure(2); hold off; ax = gca;
showPhenotype(genomes,d,1.2,ax); axis equal;

[fitness,phenotypes] = fitfun(genomes,d);

%% Train latent model

pm.map.model = trainFeatures(phenotypes,m);

%% Show latent model reconstruction on training data
[~,flatPhenotypes] = getPhenotypeBoolean(phenotypes, pm.map.model.encoderLG.Layers(1).InputSize(1));

features = getPrediction(flatPhenotypes,pm.map.model);

clear input;
input(1,1,:,:) = features';
input = dlarray(input,'SSCB');
generatedImage = sigmoid(predict(pm.map.model.decoderNet, input));
generatedImage = extractdata(generatedImage);
fig(3) = figure;
imshow(imtile(generatedImage, "ThumbnailSize", [d.resolution,d.resolution]))
title("Generated by VAE by varying two dimensions, before retraining, iteration 1");

save([DOMAIN '_step1.mat']);

%%
fig(4) = figure(4); hold off; ax = gca;
showPhenotype(genomes,d,1.2,ax,3*features);



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Run POEM's first iteration
[map{hypID}, config{hypID}, results{hypID}] = poem(initSamples,polygons,fitness,pm,d,2);
save([DOMAIN '_step1.mat']);
disp('HyperPref Step 1 Done');

%% Reload and extract results of first iteration and select IDs of shapes
load([DOMAIN '_step1.mat']);
[genes,fitness,features,bins] = extractMap(results{1}.maps{1});
% Visualization
colors = [zeros(size(genes,1),1) fitness zeros(size(genes,1),1)];            
showPhenotype(genes, d, 1.1, [], bins, colors); title('1st Iteration Result');
fig(1) = gcf;

%% show random sampling of latent space of VAE trained on random inputs.
clear input;

rr = randn(m.configuration.latentDim-2,1); % set 14 out of the 16 coordinates
x = -3:0.5:3; y = x;
[X,Y] = ndgrid(x,y);
varyCoords = [X(:),Y(:)]';
rawInput = [varyCoords;repmat(rr,1,size(varyCoords,2))];
randID = randi(m.configuration.latentDim,1,1);
rawInput([randID 1],:)=rawInput([1 randID],:);
randID = randi(m.configuration.latentDim,1,1);
rawInput([randID 2],:)=rawInput([2 randID],:);

input(1,1,:,:) = rawInput;
input = dlarray(input,'SSCB');
decoderNet = results{hypID}.models(1).decoderNet;
generatedImage = sigmoid(predict(decoderNet, input));
generatedImage = extractdata(generatedImage);
fig(2) = figure;
imshow(imtile(generatedImage, "ThumbnailSize", [d.resolution,d.resolution]))
title("Generated by VAE by varying two dimensions, before retraining, iteration 1");


%% in-distribution
[phenotypes,ctlPts] = d.getPhenotype(genes);
modelPost1 = trainFeatures(phenotypes,pm.model);
%%
clear input;

rr = randn(m.configuration.latentDim-2,1); % set 14 out of the 16 coordinates
x = -3:0.5:3; y = x;
[X,Y] = ndgrid(x,y);
varyCoords = [X(:),Y(:)]';
rawInput = [varyCoords;repmat(rr,1,size(varyCoords,2))];
randID = randi(m.configuration.latentDim,1,1);
rawInput([randID 1],:)=rawInput([1 randID],:);
randID = randi(m.configuration.latentDim,1,1);
rawInput([randID 2],:)=rawInput([2 randID],:);

input(1,1,:,:) = rawInput;
input = dlarray(input,'SSCB');
decoderNet = modelPost1.decoderNet;
generatedImage = sigmoid(predict(decoderNet, input));
generatedImage = extractdata(generatedImage);
fig(3) = figure;
imshow(imtile(generatedImage, "ThumbnailSize", [d.resolution,d.resolution]))
title("Generated by VAE by varying two dimensions, after retraining, iteration 1");

save_figures(fig, '.', 'hyperprefVAE', 12, [5 5])

%% Selection
currentSelection = randi(numel(fitness)); % In this demo, select one random shape
d.selection.models{hypID} = results{hypID}.models; % Save user model to use as constraint model

showPhenotype(genes(currentSelection,:),d,1.1,[]); title('Injected Perturbations of Selection');
fig(4) = gcf;

%%
phenotypes = d.getPhenotype(genes);
d.selection.selected{hypID} = features(currentSelection,:); 
d.selection.deselected{hypID} = features; d.selection.deselected{hypID}(currentSelection,:) = [];

hypID = hypID + 1;
newSamples = genes(currentSelection,:);
nNewPerSelected = ceil(pm.map.numInitSamples./length(currentSelection));
% Perturb selected shapes
for i=1:length(currentSelection)
    %newSampleMutations = pm.mutSelection * randn(nNewPerSelected,d.dof);
    newSampleMutations = 0.1 * randn(nNewPerSelected,d.dof);
    newSamples = [newSamples; genes(currentSelection(i),:) + newSampleMutations];
end
[newSamplesfitness,newSamplespolygons] = fitfun(newSamples,d); % Recalculate fitness! (User selection influences fitness values)
            
figure(99);plot(sort(newSamplesfitness));hold on;
showPhenotype(newSamples,d,1.1,[]); title('Injected Perturbations of Selection');

%% Run POEM's second iteration based on the user selection
[map{hypID}, config{hypID}, results{hypID}] = poem(newSamples,newSamplespolygons,newSamplesfitness,pm,d,2);
save([DOMAIN '_step2.mat']);
disp('HyperPref Step 2 Done');

%% Reload and extract results of third iteration and visualize
load([DOMAIN '_step2.mat']);
[genes,fitness,features,bins] = extractMap(results{2}.maps{1});
% Visualization
colors = [zeros(size(genes,1),1) fitness zeros(size(genes,1),1)];            
showPhenotype(genes, d, p.featureResolution(1), [], bins, colors); title('1st Iteration Result');

